import * as TEAL from "./import.ts";

export default (app) => {
  app.component("tl-button", TEAL.TlButton);
  app.component("tl-space", TEAL.TlSpace);
  app.component("tl-tooltip", TEAL.TlTooltip);
  app.component("tl-checkbox", TEAL.TlCheckbox);
  app.component("tl-checkbox-group", TEAL.TlCheckboxGroup);
  app.component("tl-switch", TEAL.TlSwitch);
  app.component("tl-text", TEAL.TlText);
  app.component("tl-icon", TEAL.TlIcon);
  app.component("tl-input", TEAL.TlInput);
  app.component("tl-input-number", TEAL.TlInputNumber);
  app.component("tl-radio", TEAL.TlRadio);
  app.component("tl-radio-group", TEAL.TlRadioGroup);
  app.component("tl-rate", TEAL.TlRate);
  app.component("tl-slider", TEAL.TlSlider);
  app.component("tl-textarea", TEAL.TlTextArea);
  app.component("tl-upload", TEAL.TlUpload);
  app.component("tl-form", TEAL.TlForm);
  app.component("tl-form-item", TEAL.TlFormItem);
  app.component("tl-dropdown", TEAL.TlDropdown);
  app.component("tl-dropdown-item", TEAL.TlDropdownItem);
  app.component("tl-title", TEAL.TlTitle);
  app.component("tl-paragraph", TEAL.TlParagraph);
  app.component("tl-link", TEAL.TlLink);
  app.component("tl-scrollbar", TEAL.TlScrollbar);
  app.component("tl-pagination", TEAL.TlPagination);
  app.component("tl-avatar", TEAL.TlAvatar);
  app.component("tl-avatar-group", TEAL.TlAvatarGroup);
  app.component("tl-badge", TEAL.TlBadge);
  app.component("tl-collapse", TEAL.TlCollapse);
  app.component("tl-collapse-group", TEAL.TlCollapseGroup);
  app.component("tl-empty", TEAL.TlEmpty);
  app.component("tl-image", TEAL.TlImage);
  app.component("tl-breadcrumb", TEAL.TlBreadcrumb);
  app.component("tl-breadcrumb-item", TEAL.TlBreadcrumbItem);
  app.component("tl-divider", TEAL.TlDivider);
  app.component("tl-image-preview-group", TEAL.TlImagePreviewGroup);
  app.component("tl-image-preview", TEAL.TlImagePreview);
  app.component("tl-tree", TEAL.TlTree);
  app.component("tl-table", TEAL.TlTable);
  app.component("tl-table-column", TEAL.TlTableColumn);
};
